version: "3.8"

services:
  db:
    # replace 'mongo-replica' with the name and tag
    # you give to your image
    image: mongo-replica:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
