import { GET_QUOTES } from "@/graphql/methods/query";
import client from "@/lib/client";
import styles from "@/styles/Home.module.css";
import { Inter } from "@next/font/google";
import { Quote } from "@prisma/client";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

type Props = {
  quotes: Quote[];
};

export default function Home({ quotes }: Props) {
  return (
    <>
      <Head>
        <title>Quotible</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <p className={styles.title}>Welcome to Quotible</p>
        </div>
        <div className={styles.quoteList}>
          {quotes.map((item: Quote, index: number) => {
            return (
              <div key={index} className={styles.quoteBody}>
                <p className={styles.tag}>{item.tag}</p>
                <p>{item.content}</p>
                <p className={styles.author}>- {item.author}</p>
              </div>
            );
          })}
        </div>
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  const { data } = await client.query({
    query: GET_QUOTES,
  });

  return {
    props: {
      quotes: data.quotes,
    },
  };
};
